name: Download uberjar for E2E tests
description: Download either a freshly built artifact or the one built in one of the previous commits.
inputs:
  edition:
    description: Metabase edition.
    required: true

runs:
  using: "composite"
  steps:
    - name: Download previously stored uberjar
      uses: actions/github-script@v6
      with:
        script: | # js
          const fs = require('fs');
          const execSync = require("child_process").execSync;
          const artifact = require('@actions/artifact');
          const artifactClient = artifact.create();

          const getCommit = (ref = "HEAD") => {
            const [commit] = execSync(`git rev-parse ${ref}`, { encoding: "utf8" }).split(
              "\n",
            );
            return commit;
          };

          const baseConfig = {
            owner: context.repo.owner,
            repo: context.repo.repo,
          };

          async function getArtifact(commit, depth = 0) {
            if (depth > 20) {
              throw new Error("Couldn't find the artifact!");
            }

            const artifactName = `metabase-${{ inputs.edition }}-${commit}-uberjar`;
            console.log(artifactName);
            const downloadResponse = await artifactClient.downloadArtifact(artifactName);
            console.log(downloadResponse)
          }

          const currentCommit = "8808c728ca643d9f9f2a97b1cba58eb6033f48e8";
          getArtifact(currentCommit);

    - name: Unzip Metabase artifact containing an uberjar
      run: unzip mb.zip
      shell: bash

    - name: Get the version info
      run: |
        jar xf target/uberjar/metabase.jar version.properties
        cat version.properties
        mv version.properties resources/
      shell: bash
